title:              YL Blog
email:              whywhygood@gmail.com
description:        A Blog by YL
author:             Yudi Lin
baseurl:            ""
url:                "https://yudilin.github.io/"


# Social Profiles
twitter_username:   
github_username:    yudilin
facebook_username:  
instagram_username:  
linkedin_username:  yudi-lin

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
